### ISSUE TITLE
Final Version

### ISSUE THREAD

**Issue by mritzmann** [republique-et-canton-de-geneve/chvote-1-0#30]
According to [various sources](https://www.rts.ch/info/regions/geneve/10028542-le-canton-de-geneve-renonce-a-sa-plate-forme-de-vote-electronique.html), this e-voting platform will be discontinued by the Canton of Geneva. The last commits are several months old. In the meantime, have there been any changes that haven't been pushed yet? If so, this would be a good time before Canton Geneva runs out of time or money to maintain this repository.

It would be great if all the code would be available here. According to the motto: Public Money, Public Code!

**Comment by chvote-etat-de-geneve** [comment]
Hi,

Sorry for the delay to make a response. The source code for the offline administration application of the current chvote 1.0 system has not been changed for a while.

The team has been working hard on a new 2.0 version whose source code will be released in january 2019. This new version will however never be put into production as the project has been stopped.

**Comment by D4rkMindz** [comment]
So if you are working on version 2.0, why isn't it officially linked here?
[republique-et-canton-de-geneve/chvote-protocol-poc](https://github.com/republique-et-canton-de-geneve/chvote-protocol-poc)

Wouldn't it be better (and also more usual) to work with the [Git Flow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) and also integrate version 2.0 here or in e.g. a repo called `republique-et-canton-de-geneve/chvote`?
The development of the application would be better traceable and could be more easily passed on to external parties/other departements.

**Comment by chvote-etat-de-geneve** [comment]
Hi, the version 2.0 is a completely different project than version 1.0. It doesn't share anything with the former version, the scope being completely different. As a consequence, it is not a new branch on the current repository being published, but a brand new project including dozens of repositories.

We will hopefully publish the new version in april 2019 (requirements external to the development team bind us to wait until this date), in the state it is since the project has been halted. It will be published on gitlab.com (we moved to this repository manager for the development of the new platform for technical reasons), and a link will be included in the current publication on github.

**Comment by gagarine** [comment]
So the project what technically overkill, driving the cost up to the point to kill the project? ;) 

I well aware than the official story is that other Canton didn't participate. And it's certainly a shame they didn't. But would it be manageable without them? At no point, I saw in the historical parliamentary discussion that the project required other cantons to participate.

**Comment by chvote-etat-de-geneve** [comment]
Hi, thank you for your comment! However, we only reply to technical requests on this github channel. If you wish to ask those questions to the right persons, please contact directly the State Chancellery of Geneva on one of their own channels: https://www.ge.ch/organisation/chancellerie-etat or https://twitter.com/GE_chancellerie.

Kind regards.

**Comment by mritzmann** [comment]
In the meantime some time has passed and the interest is probably not there anymore anyway. For this reason I am closing this issue.
